### ISSUE TITLE
Allow for more flexible naming conventions

### ISSUE THREAD

**Issue by tam5** [spatie/package-sync#15]
Currently, skeleton repositories must be named `*-php` and `*-laravel`, and likewise laravel apps must be named `laravel-*`.

I was wondering if you might be open to a PR that allows this to be more flexible. I'd love to use this to sync our packages/apps but we don't necessarily follow the same naming convention as spatie.

I could see a few ways this might work.

I think one way that only requires a very minimal change would be to introduce a new section in the yaml config which allows to specify the regexes that should be used. For example:

```yml
  templates:
    # github organization name
    vendor: spatie
    # skeleton repositories, with their corresponding regex.
    # the skeleton is used if the name of the package being
    # analyzed or fixed matches the defined regex.
    names:
      package-skeleton-laravel: laravel-.* 
      package-skeleton-php: .*
```

I think with this setup everything can work as it does today, but new rules can also be used to determine what skeleton to use when necessary. 

An alternative might be to get something like this to work:

```sh
./dist/package-sync --config package-sync.yml --template my-vendor/my-template-repo analyze my-laravel-app
```

I quite like that approach as well, but it's a bit of a bigger change.

Let me know what you think, and I can open PR.
